---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	input_validation(input_validation)
	input_rejection(input_rejection)
	agent(agent)
	output_validation(output_validation)
	error_handler(error_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> input_validation;
	agent --> output_validation;
	input_validation -. &nbsp;continue&nbsp; .-> agent;
	input_validation -. &nbsp;reject&nbsp; .-> input_rejection;
	output_validation -. &nbsp;success&nbsp; .-> __end__;
	output_validation -. &nbsp;error&nbsp; .-> error_handler;
	error_handler --> __end__;
	input_rejection --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
